### ISSUE TITLE
Box Art and Game Logo Hidden by Video Snap

### ISSUE THREAD

**Issue by virtuallywired** [anthonycaccese/es-theme-crt#2]
Im not if it just my install, I'm using Pi 4 8GB, latest RetroPie and used Skyscraper to scrape the media. The Box Art and Game logo hidden by the video. See my video I uploaded > https://www.icloud.com/sharedalbum/#B0kGtue8VJG1nso;F3EEA1EF-97D9-4D17-AB6C-DF58518F35B2

**Comment by anthonycaccese** [comment]
Can you let me know which video player you are using for playback in EmulationStation?

While in EmulationStation, press the START button, which will open the ES options menu where you can change a few things.

While in this menu, scroll down until you find "Other Options" or something similar.

From that menu, you'll see an option that says "Use OMX Player". Let me know if that is set to “on”

If its set to “on”... that is why the video is showing over the artwork. OMXPlayer does not support layering in any theme.  So you will need to switch that off.

**Comment by virtuallywired** [comment]
Thank you so much, another enthusiast advised me to change the z-index, but disabling OMXPlayer worked.
